version: '3.9'

services:
  backend:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: RotReport
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: RotReport
      DATABASE_HOST: postgres
    ports:
      - 5432:5432